import SessionTemplate from "../components/SeccionTemplate"
import "../components/sessions-styles/FirstVersion.scss"
import "../App.scss"
import {motion, useScroll, useTransform} from "framer-motion"
import { useRef } from "react"

export default function FirstVersion() {
  const containerRef = useRef(null);
  const { scrollYProgress } = useScroll({
    target: containerRef,
    offset: ["start start", "end end"]
  });

  // Definimos la transición de opacidad y escala para el efecto de superposición
  // La imagen 1 desaparece a la mitad del scroll, mientras la 2 aparece
  const opacity1 = useTransform(scrollYProgress, [0, 0.45, 0.55], [1, 1, 0]);
  const scale1 = useTransform(scrollYProgress, [0, 0.45, 0.55], [1, 1, 0.9]);
  
  const opacity2 = useTransform(scrollYProgress, [0.45, 0.55, 1], [0, 1, 1]);
  const scale2 = useTransform(scrollYProgress, [0.45, 0.55, 1], [0.9, 1, 1]);

  return (
    <SessionTemplate title={"First Version"}>
      <div className="title-section">
        <h2>OBJECTIVE: "Create the first version of the prototype to test with users."</h2>
      </div>

      {/* Section 1: Collage Template */}
      <div className="collage-section">
        <div className="collage-grid">
          <div className="collage-item collage-item-1"></div>
          <div className="collage-item collage-item-2"></div>
          <div className="collage-item collage-item-3"></div>
          <div className="collage-item collage-item-4"></div>
          <div className="collage-item collage-item-5"></div>
          <div className="collage-item collage-item-6"></div>
        </div>
      </div>

      <hr className="divider" />

      {/* Section 2: Process Description */}
      <div className="process-description">
        <motion.p 
          className="intro-text"
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, amount: 0.3 }}
          transition={{ duration: 0.8 }}
        >
          These are some of the scenes from the development of our proposed solution.
        </motion.p>

        <div className="materials-section">
          <h3>Materials:</h3>
          <ul className="materials-list">
            <li><span className="label">Video generation AI:</span> Synestesia, Canva, Flixier, Deevid AI</li>
            <li><span className="label">Video editor:</span> Canva</li>
            <li><span className="label">Subtitling:</span> TikTok</li>
            <li><span className="label">Voice generator:</span> Fish AI</li>
            <li><span className="label">AI image generator:</span> Freepik</li>
            <li><span className="label">Script:</span> Chat GPT</li>
          </ul>
        </div>

        <div className="steps-section">
          <h3>Description:</h3>
          <ol className="steps-list">
            <li>
              <span className="step-number">1.</span>
              <span className="step-text">First, we access Chat GPT and select the "Skeleton Shorts" group.</span>
            </li>
            <li>
              <span className="step-number">2.</span>
              <span className="step-text">Then, we discuss the topic we want to cover in the chat, and it will generate a prompt for images.</span>
            </li>
            <li>
              <span className="step-number">3.</span>
              <span className="step-text">Using the prompt for images, we use the image generation tool to create each scene.</span>
            </li>
            <li>
              <span className="step-number">4.</span>
              <span className="step-text">Finally, we type another documented prompt that will allow us to generate a prompt to create a video for each scene.</span>
            </li>
            <li>
              <span className="step-number">5.</span>
              <span className="step-text">Next, using the image, we go to the AI video generation tool and paste the corresponding scene from your ad, until our multimedia file is ready.</span>
            </li>
            <li>
              <span className="step-number">6.</span>
              <span className="step-text">Then, we open a video editor and load all the videos generated by the AI.</span>
            </li>
            <li>
              <span className="step-number">7.</span>
              <span className="step-text">For the script, we again ask ChatGPT to generate a script for each scene.</span>
            </li>
            <li>
              <span className="step-number">8.</span>
              <span className="step-text">With the script it provides, we paste it into the voice generator to load an audio narration of the respective text.</span>
            </li>
            <li>
              <span className="step-number">9.</span>
              <span className="step-text">We paste each audio fragment into the editor.</span>
            </li>
            <li>
              <span className="step-number">10.</span>
              <span className="step-text">We upload the complete video from the video editor.</span>
            </li>
            <li>
              <span className="step-number">11.</span>
              <span className="step-text">Finally, in TikTok, we automatically generate the subtitles and upload the video, ready to be published.</span>
            </li>
          </ol>
        </div>
      </div>
    </SessionTemplate>
  )
}